-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 18:23:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(250) NULL DEFAULT 'url',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direcciones` (
  `id` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `foto` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`profesionales_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesionales_productos` (
  `id` INT NOT NULL,
  `producto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesionales` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(250) NULL,
  `usuario_id` INT NULL,
  `PROFESION` ENUM("Otros") NOT NULL DEFAULT 'Otros',
  `direccion_id` INT NULL,
  `profesional_producto_id` INT NULL,
  `cbu` VARCHAR(45) NOT NULL,
  `clasificacion` INT NULL,
  `orden_id` INT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profesion_UNIQUE` (`PROFESION` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `direccion_id_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `profesional_producto_id_idx` (`profesional_producto_id` ASC) VISIBLE,
  INDEX `orden_id_idx` (`orden_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direccion_id`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profesional_producto_id`
    FOREIGN KEY (`profesional_producto_id`)
    REFERENCES `mydb`.`profesionales_productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_id`
    FOREIGN KEY (`orden_id`)
    REFERENCES `mydb`.`ordenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenes` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `profesional_id` INT NULL,
  `precio` DECIMAL(18,2) NULL,
  `fecha` DATE NOT NULL,
  `ESTADO` ENUM("Inicial", "Pendiente", "Aprobada") NOT NULL DEFAULT 'Inicial',
  PRIMARY KEY (`id`),
  INDEX `profesional_id_idx` (`profesional_id` ASC) VISIBLE,
  CONSTRAINT `profesional_id`
    FOREIGN KEY (`profesional_id`)
    REFERENCES `mydb`.`profesionales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compras_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compras_productos` (
  `id` INT NOT NULL,
  `producto_id` INT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compras` (
  `id` INT NOT NULL,
  `compra_producto_id` INT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`compra_producto_id` ASC) VISIBLE,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`compra_producto_id`)
    REFERENCES `mydb`.`compras_productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(150) NULL,
  `usuario_id` INT NULL,
  `direccion_id` INT NULL,
  `clasificacion` TINYINT NULL,
  `orden_id` INT NULL,
  `compra_id` INT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `direccion_id_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `orden_id_idx` (`orden_id` ASC) VISIBLE,
  INDEX `compra_id_idx` (`compra_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direccion_id`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_id`
    FOREIGN KEY (`orden_id`)
    REFERENCES `mydb`.`ordenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_id`
    FOREIGN KEY (`compra_id`)
    REFERENCES `mydb`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
