CREATE DATABASE if NOT EXISTS service DEFAULT CHARACTER SET UTF8 collate UTF8_SPANISH_CI;

USE service;

CREATE TABLE IF NOT EXISTS clientes (
id LONG UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
dni  VARCHAR(50),

usuario INT UNSIGNED,
FOREIGN KEY (usuario) REFERENCES usuarios (id)
);